### ISSUE TITLE
Latest version config generation error.

### ISSUE THREAD

**Issue by Pordy** [delax/Enviromine-Configs#4]
Hy!

The latest EnviroMine-1.3.124.jar generates this config for me:

I cannot turn off the unwanted physics.
Any solution?

# Configuration file

Config {
    # [DISABLED][WIP] Temporarily overrides client configurations with the server's (NETWORK INTESIVE!)
    B:"Client Config Override (SMP)"=false

    # Override Profile. It Can be used for servers to force profiles on servers or modpack. This Overrides any world loaded up. Name is Case Sensitive!
    B:"Override Profile"=false
    S:Profile=default
}

"Do not Edit" {
    S:"Current Config Version"=1.0.0
}

Gases {
    # Disables all gases and slowly deletes existing pockets
    B:"Disable Gases"=false

    # How many gases can be processed in a single pass per chunk (-1 = infinite)
    I:"Gas Pass Limit"=-1

    # How many ticks between gas updates. Gas fires are 1/4 of this.
    I:"Gas Tick Rate"=32

    # List of Blocks that will ignite flamable gasses. [default: [minecraft:flowing_lava], [minecraft:lava], [minecraft:torch], [minecraft:lit_furnace], [minecraft:fire], [enviromine:firegas], [enviromine:firetorch], [enviromine:burningcoal]]
    S:"Ignite List" <
        minecraft:flowing_lava
        minecraft:lava
        minecraft:torch
        minecraft:lit_furnace
        minecraft:fire
        enviromine:firegas
        enviromine:firetorch
        enviromine:burningcoal
     >

    # Whether to render gases not normally visible
    B:"Render normal gas"=false

    # Normal gases will move extremely slowly and reduce TPS lag
    B:"Slow Gases"=true

    # Whether gases should spread like water (faster) or even out as much as possible (realistic)
    B:"Water like spreading"=true
}

Physics {
    # How long until individual chunk's physics starts after loading (DO NOT SET TOO LOW)
    I:"Chunk Physics Delay"=1000

    # This will change maximum number of blocks that can be updated with physics at a time. - 1 = Unlimited
    I:"Consecutive Physics Update Cap"=128

    # Setting Large Ice Cracking to true can cause Massive Lag
    B:"Large Ice Cracking"=false

    # The number of ticks between physics update passes (must be 6 or more)
    I:"Physics Interval"=6

    # 0 = No action, 1 = Limit to < 100 per 8x8 block area, 2 = Delete excessive entities & Dump physics (EMERGENCY ONLY)
    I:"Physics entity fail safe level"=1

    # How long after world start until the physics system kicks in (DO NOT SET TOO LOW)
    I:"World Start Delay"=1000
}

Potions {
    I:Dehydration=35
    B:"Enable Frostbite"=true
    B:"Enable Heat Stroke"=true
    B:"Enable Hypothermia"=true
    I:Frostbite=34
    I:"Heat Stroke"=33
    I:Hypothermia=32
    I:Insanity=36
}

"World Generation" {
    # Generates massive abandoned mineshafts (size doesn't cause lag) (This Overrides all Dimensions. Check Custom Dimension properties if you want to set it only for certain Dimensions.)
    B:"Enable New Abandoned Mineshafts"=true

    # Generates mineshafts in villages
    B:"Enable Village MineShafts"=true
    B:"Generate Gases"=true
}

general {
    B:"Blindness instead of Nausea"=false
    B:"Check For Updates"=true
    B:"Finite Water"=false
    B:"Keep statuses on death"=false

    # Render 3d gear worn on player. Must reload game to take effect
    B:"Render Gear"=true
}

**Comment by delax** [comment]
The 1.3 version I made is kinda a mess, I tried to port my 1.2 config to 1.3 and it wasn't working very well.
I am working on simply re-making it from scratch, I could upload what I got if anyone was interested.

**Comment by delax** [comment]
And as for your actual question.
If you want **all** physics added by enviromine gone:
In _config\enviromine\profiles\deault\default_Settings.cfg_ find `B:"Enable Physics"=true` and change `true` to `false`.
Nearby are a host of other settings you may want too: food spoiling, torch burn out, sanity, etc.

Changing physics for a specific block is slightly more complex.
